### ISSUE TITLE
Creating image error

### ISSUE THREAD

**Issue by jcarolinares** [jcarolinares/qwertee-scrapper#1]
Traceback (most recent call last):
  File "/home/jcarolinares/proyectos/qwertee-scrapper/qwertee_scrapper.py", line 132, in <module>
    main()
  File "/home/jcarolinares/proyectos/qwertee-scrapper/qwertee_scrapper.py", line 94, in main
    wallpaper.paste(t_shirt_list[total_index].img, (img_x*index, img_y * v_index, img_x+index*img_x, img_y+img_y*v_index) )
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1330, in paste
    self.im.paste(im, box)
ValueError: images do not match

**Comment by jcarolinares** [comment]
Something is happening with the creation of the image

**Comment by jcarolinares** [comment]
I Love You 3000
x=255
y=256

Y is not true, in reality is y=306

What is happening with Y

**Comment by jcarolinares** [comment]
It's related with a wrong metada inside the "i love you so much" web/image. Working with others images. Changed to a fiex size of 255,306 to prevent future errors
